# Workflow name
name: Python CI with UV

# Run workflow when code is pushed to main
on:
  push:
    branches: [ main ]

jobs:
  build:

    # GitHub creates a temporary Ubuntu machine
    runs-on: ubuntu-latest

    steps:

      # Step 1: Download repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Install Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # Step 3: Install uv
      - name: Install uv
        run: pip install uv

      # Step 4: Cache uv dependencies
      - name: Cache uv dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ hashFiles('uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      # Step 5: Install dependencies
      - name: Install dependencies
        run: uv sync

      # Step 6: Verify project imports
      - name: Verify project imports
        run: |
          uv run python - <<EOF